{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "89a3869f-a62b-4778-9817-c460385a6279",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import sqlite3\n",
    "\n",
    "def save_movie():\n",
    "    title = title_entry.get()\n",
    "    genre = genre_combo.get()\n",
    "\n",
    "    if not title:\n",
    "        status_label.config(text=\"Please enter a movie title ❌\")\n",
    "        return\n",
    "\n",
    "    conn = sqlite3.connect(\"movies.db\")\n",
    "    cursor = conn.cursor()\n",
    "\n",
    "    # Create table without the 'year' column\n",
    "    cursor.execute(\"\"\"\n",
    "    CREATE TABLE IF NOT EXISTS movies (\n",
    "        id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "        title TEXT,\n",
    "        genre TEXT\n",
    "    )\n",
    "    \"\"\")\n",
    "\n",
    "    # Insert movie\n",
    "    cursor.execute(\n",
    "        \"INSERT INTO movies (title, genre) VALUES (?, ?)\",\n",
    "        (title, genre)\n",
    "    )\n",
    "    conn.commit()\n",
    "\n",
    "    # Fetch all movies to update display\n",
    "    cursor.execute(\"SELECT title, genre FROM movies\")\n",
    "    movies = cursor.fetchall()\n",
    "    conn.close()\n",
    "\n",
    "    # Clear the listbox and insert all movies\n",
    "    movie_listbox.delete(0, tk.END)\n",
    "    for m in movies:\n",
    "        movie_listbox.insert(tk.END, f\"{m[0]} - {m[1]}\")\n",
    "\n",
    "    status_label.config(text=\"Movie saved successfully ✅\")\n",
    "    title_entry.delete(0, tk.END)\n",
    "    genre_combo.set(\"\")\n",
    "\n",
    "# ---------- GUI ----------\n",
    "root = tk.Tk()\n",
    "root.title(\"Favorite Movie Tracker\")\n",
    "root.geometry(\"400x400\")  # bigger to fit the listbox\n",
    "\n",
    "tk.Label(root, text=\"Favorite Movie Tracker\", font=(\"Arial\", 14)).pack(pady=10)\n",
    "\n",
    "tk.Label(root, text=\"Movie Title\").pack()\n",
    "title_entry = tk.Entry(root)\n",
    "title_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Genre\").pack()\n",
    "genre_combo = ttk.Combobox(\n",
    "    root, values=[\"Action\", \"Comedy\", \"Drama\", \"Sci-Fi\", \"Horror\"]\n",
    ")\n",
    "genre_combo.pack()\n",
    "\n",
    "save_btn = tk.Button(root, text=\"Save Movie\", command=save_movie)\n",
    "save_btn.pack(pady=10)\n",
    "\n",
    "status_label = tk.Label(root, text=\"\")\n",
    "status_label.pack()\n",
    "\n",
    "# Listbox to show saved movies\n",
    "movie_listbox = tk.Listbox(root, width=50)\n",
    "movie_listbox.pack(pady=10)\n",
    "\n",
    "# Load existing movies on startup\n",
    "def load_movies():\n",
    "    conn = sqlite3.connect(\"movies.db\")\n",
    "    cursor = conn.cursor()\n",
    "    cursor.execute(\"CREATE TABLE IF NOT EXISTS movies (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, genre TEXT)\")\n",
    "    cursor.execute(\"SELECT title, genre FROM movies\")\n",
    "    movies = cursor.fetchall()\n",
    "    conn.close()\n",
    "    for m in movies:\n",
    "        movie_listbox.insert(tk.END, f\"{m[0]} - {m[1]}\")\n",
    "\n",
    "load_movies()\n",
    "root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
